/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#964900',
        'primary-container': '#f57c00',
        'on-primary': '#ffffff',
        'on-primary-container': '#572800',
        'primary-fixed': '#ffdcc6',
        'primary-fixed-dim': '#ffb786',
        'on-primary-fixed': '#311300',
        'on-primary-fixed-variant': '#723600',
        'secondary': '#705d00',
        'secondary-container': '#fdd400',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6f5c00',
        'secondary-fixed': '#ffe170',
        'tertiary': '#006e1c',
        'tertiary-container': '#4eb152',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#003e0c',
        'tertiary-fixed': '#94f990',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-container': '#eeeeee',
        'surface-container-low': '#f3f3f3',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#574235',
        'on-background': '#1a1c1c',
        'outline': '#8b7263',
        'outline-variant': '#dec1af',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
        'inverse-primary': '#ffb786',
      },
      fontFamily: {
        'sans': ['Be Vietnam Pro', 'sans-serif'],
        'heading': ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
